version: '3.8'
services:
   redis:
     image: redis
     restart: always
   postgres:
     image: postgres:16.1
     restart: always
     container_name: postgres
     env_file:
       - ./.env
     volumes:
       - dbdata:/var/lib/postgresql/data/
   webapp:
     volumes:
       - ".:/app"
     restart: always
     container_name: 'api'
     build:
       context: .
     ports:
         - "8000:8000"
     command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
     env_file:
       - ./.env
     depends_on:
       - postgres
   celeryworker:
     restart: always
     build:
       context: .
     volumes:
         - ".:/app"
     command: ["celery", "--workdir=/app", "-A", "customBilly", "worker", "--loglevel=DEBUG"]
   celery-beat:
     build: .
     command: celery -A customBilly beat -l info
     volumes:
       - ".:/app"
     depends_on:
       - redis

volumes:
  dbdata: