# Generated by Django 4.2.7 on 2024-01-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Amount'),
        ),
    ]
