# Generated by Django 4.2.7 on 2023-11-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billy', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Last Name'),
        ),
    ]
