# Generated by Django 4.2.7 on 2023-11-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billy', '0003_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
    ]
