# Generated by Django 4.2.7 on 2023-11-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billy', '0004_alter_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(default='', max_length=500, verbose_name='Description'),
        ),
    ]
