# Generated by Django 4.2.7 on 2023-11-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billy', '0009_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='points_count',
            field=models.IntegerField(default=0, verbose_name='Points count'),
        ),
    ]
