# Generated by Django 4.2.7 on 2023-11-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billy', '0010_alter_pointtransaction_points_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='points_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Points count'),
        ),
    ]
