# Generated by Django 4.2.7 on 2023-11-24 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billy', '0012_remove_pointtransaction_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtransaction',
            name='sender',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='billy.profile'),
            preserve_default=False,
        ),
    ]
