# Generated by Django 4.2.7 on 2023-11-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billy', '0014_alter_profile_role_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Manager'), (2, 'Employee')], default=2),
        ),
    ]
