# Generated by Django 4.2.7 on 2023-12-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billy', '0016_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
