# Generated by Django 4.2.7 on 2023-12-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billy', '0017_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='points',
        ),
    ]
