# Generated by Django 4.2.7 on 2023-12-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billy', '0019_alter_order_product_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointTransaction',
        ),
    ]
