# Generated by Django 4.2.7 on 2023-12-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billy', '0020_delete_pointtransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
